routes/web.php
<?php

Auth::routes();

Route::get('/', 'loginController@index')->name('loginPage');

Route::group(['middleware' => ['auth']], function(){
    Route::group(['middleware' => ['notEmployee']], function() {
        Route::get('/laundry/applying', 'TokoController@applying')->name('laundry.applying');
        Route::get('/user/out', 'PegawaiController@out')->name('user.out');
    });
    Route::group(['middleware' => ['hasntLaundry']], function() {
        Route::get('/laundry', 'TokoController@index')->name('laundry.index');
        Route::get('/laundry/create', 'TokoController@create')->name('laundry.create');

        Route::post('/laundry/store', 'TokoController@store')->name('laundry.store');
        Route::post('/user/apply', 'PegawaiController@apply')->name('user.apply');
    });
    Route::group(['middleware' => ['hasLaundry']], function() {
        Route::get('/user/{id_pegawai}/{role}', 'PegawaiController@hire')->name('user.hire');
        Route::get('/transaksi/done/{id_trans}', 'TransaksiController@done')->name('transaksi.done');
        Route::get('/ekstra/addekstra', 'EkstraController@addekstra')->name('ekstra.addnew');

        Route::resource('/laundry', 'TokoController')->except(['index','create','store']);
        Route::resource('/user', 'PegawaiController');
        Route::resource('/transaksi', 'TransaksiController');
        Route::resource('/transaksi/ekstra', 'EkstraController');
//        Route::post('/mail/send', 'MailController@send')->name('send');
        Route::get('/mail/send/{data}', 'MailController@send')->name('send');

    });
});

?>

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Scripts -->
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    {{--<script src="{{ asset('js/bootstrap.js') }}"></script>--}}
    {{--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>--}}
    {{--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>--}}
    {{--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>--}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
</head>
<body>
    <div id="app">
        @yield('sidebar')
        <div class="right">
            <nav class="navbar navbar-expand-md navbar-light bg-white">
                <div class="container">
                    <a class="navbar-brand slf-navbar-title" href="{{ url('/') }}">
                        {{ config('app.name') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                                <li class="nav-item">
                                    @if (Route::has('register'))
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    @endif
                                </li>
                            @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle header-name" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{explode(' ',trim( Auth::user()->name ))[0]}}<span class="caret"></span>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4 content">
                @yield('content-nosidebar')
                @yield('body')
            </main>
        </div>
    </div>
</body>
</html>

resources/views/admin/applying.blade.php
@extends('admin.app')

@section('content-nosidebar')

    <div class="container">
        <div class="row vertical-align">

            <center>
                <h1 style="margin-bottom:0px"><span style="font-weight: 100;">Anda sedang mendaftar pada </span><br>{{session('nama_toko')}}</h1><br>
                <p>Tunggu pemilik laundry menerima lamaran anda</p>
                <a href="{{route('user.out')}}"><button type="button" class="btn btn-danger">Batalkan Lamaran</button></a>
                {{--<button type="button" class="btn btn-light" data-toggle="modal" data-target="#vacancy">Batalkan Lamaran</button>--}}
            </center>

        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="vacancy" tabindex="-1" role="dialog" aria-labelledby="vacancy" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Pendaftaran Pegawai</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('user.apply')}}" method="POST">
                    <div class="modal-body">
                        @csrf
                        <div class="form-group col-md-10 mx-auto">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Laundry tidak ditemukan!</strong> Periksa kode Laundry kembali.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <label for="kodeLaundry">Kode Laundry</label>
                            <input type="text" class="form-control" name="kode" id="kodeLaundry" aria-describedby="kodeHelp" placeholder="Masukkan Kode Laundry" required>
                            <small id="kodeHelp" class="form-text text-muted">Tanyakan Kode Laundry pada pemilik laundry</small>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" >Daftar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/bukaLaundry.blade.php
@extends('admin.app')

@section('content-nosidebar')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Buka Laundry') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('laundry.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="nama" class="col-md-4 col-form-label text-md-right">Nama Laundry*</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="nama" id="nama" placeholder="Liquid Laundry, Laundry Asrama" required>
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <label for="notelp" class="col-md-4 col-form-label text-md-right">No. Telp</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="no_hp" id="nama" placeholder="Nomor Telepon">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="alamat" class="col-md-4 col-form-label text-md-right">Alamat</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="alamat" id="nama" placeholder="Alamat Laundry">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Daftarkan') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('admin.app')

@section('body')

    {{--@if($data->isEmpty())--}}
        {{--@include('admin.unemp')--}}
    {{--@else--}}
        {{--{{dd($data)}}--}}
        @section('sidebar')
            @include('admin.sidebar')
        @endsection
        @yield('content')
        @include('admin.setToko')


    {{--@endif--}}


@endsection

resources/views/admin/laporan.blade.php
@extends('admin.index')

@section('content')

    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <div>
                        <h2 class="card-title">Daftar Transaksi</h2>
                    </div>
                    <hr>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                        <th>ID/No</th>
                        <th>Customer</th>
                        <th>Berat Laundry</th>
                        <th>Tanggal Masuk</th>
                        <th>Tanggal Pengambilan</th>
                        <th>Harga Total</th>
                        <th>Status</th>
                        <th>#</th>
                        </thead>
                        <tbody>
                                            {{--{{dd($data)}}--}}
                        @foreach($data as $item)
                            <tr style="cursor: pointer" > {{-- data-toggle="modal" data-target="#transDetail"--}}
                                <td>{{$item->id_trans}}</td>
                                <td>{{is_null($item->customer)? "-" : $item->customer}}</td>
                                <td>{{$item->berat.' KG'}}</td>
{{--                                {{(dd($item->created_at)->format('d m Y'))}}--}}
                                <td>{{DateTime::createFromFormat("U", strtotime($item->tglmasuk))->format('d M Y')}}</td>
                                <td>{{DateTime::createFromFormat("U", strtotime($item->duedate))->format('d M Y')}}</td>
{{--                                <td>{{is_null($item->role)?'-':$item->role}}</td>--}}
                                <td>{{'Rp.'.number_format($item->hargatotal , 0, ',', '.')}}</td>
                                <td>{{$item->done ? 'Selesai' : 'On-Process'}}</td>
                                <td>@if(!$item->done)
                                        @if(session()->has('ekstra'))
                                            <button type="button" class="btn btn-light btn-sml">Ekstra</button>
                                        @endif
                                        <a  href="{{route('transaksi.done', ['id'=>$item->id_trans])}}" ><button type="button" class="btn btn-success">Selesai</button></a>
                                    @endif
                                </td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    {{--table.table.table-striped.table-hover>(thead>(th*5))+tbody--}}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/setToko.blade.php
<!-- Modal -->
<div class="modal fade" id="setting" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Tambah Fitur</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        Fitur Cucian Tambahan
                    </div>
                    <div class="col-md-3">
                        Rp.30.000
                    </div>
                    <div class="col-md-3">
                        <a href="{{route('ekstra.addnew')}}"><button type="button" style="float:right" class="btn btn-primary">Tambah</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="transDetail" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Detail Transaksi</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="codeOnly" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mulai tambah pegawai!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-auto" style="padding-bottom: 0px;padding-top: 30px">
                    <center>
                        <div class="form-group row">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Kode Laundry Anda</label>
                                <input type="text" class="form-control form-control-lg" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Kode Laundry" value="{{session('kode_toko')}}" readonly>
                                <small id="emailHelp" class="form-text text-muted">Berikan ke calon pegawai</small>
                            </div>
                        </div>
                    </center>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Oke</button>
            </div>
        </div>
    </div>
</div>

@if(session()->has('alert') && session()->get('alert')=="modal-codeOnly")
    <script type="text/javascript">
        $('#codeOnly').modal('show');
    </script>
@endif

resources/views/admin/sidebar.blade.php
<?php
    $path = \Request::route()->getName();
?>

<div class="sidebar">
    {{--{{dd(session('role'))}}--}}
    <a class="item bars" onclick="document.getElementsByClassName('sidebar')[0].classList.toggle('collapsed');document.getElementsByClassName('menu-btn')[0].classList.toggle('fa-chevron-left');">
        <i class="fas fa-bars menu-btn"></i>
    </a>
    <a class="item {{$path=='transaksi.create'? 'active' : ''}}" href="{{route('transaksi.create')}}">{{--active--}}
        <i class="fas fa-calculator"></i>
        Kasir
    </a>
    @if(session('role') == "admin")
        <a class="item {{$path=='transaksi.index'? 'active' : ''}}" href="{{route('transaksi.index')}}">
            <i class="fas fa-sticky-note"></i>
            Laporan
        </a>
        <a class="item {{$path=='user.index'? 'active' : ''}}" href="{{route('user.index')}}">
            <i class="fas fa-user"></i>
            User
        </a>
        <a class="item" href="#" data-toggle="modal" data-target="#setting">
            <i class="fas fa-plus"></i>
            Tambah Fitur
        </a>
    @endif
</div>

resources/views/admin/transaksi.blade.php
@extends('admin.index')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="sub-content col-md-4">
                {{--{{dd(session())}}--}}
                <h1>Transaksi</h1>
                <hr>
                @if(session()->has('alert-trans') && session('alert-trans')=="success")
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        Laundry telah masuk dalam proses dengan <strong> No. {{session('id')}}</strong> dan biaya <strong>{{session('biaya')}}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @elseif(session()->has('alert-trans') && session('alert-trans')=="error")
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        laundry gagal diinput, mohon coba lagi
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                <form action="{{route('transaksi.store')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="weight">Berat Cucian*</label>
                        <div class="input-group">
                            <input type="number" step=".1" max="100" min=".1" class="form-control input-weight" name="berat" id="weight" placeholder="0" aria-label="Recipient's username" aria-describedby="basic-addon2" required autofocus>
                            <div class="input-group-append">
                                <span class="input-group-text" id="basic-addon2">KG</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pelanggan">Durasi Laundry*</label>
                        <div class="input-group mb-3 col-md-6 input-group-lg" style="padding:0!important;">
                            <select class="custom-select custom-select-lg" name="lama" id="inputGroupSelect02" required>
                                {{--<option selected disabled>Choose...</option>--}}
                                <option value=1>Satu</option>
                                <option value=2 selected>Dua</option>
                                <option value=3>Tiga</option>
                                <option value=4>Empat</option>
                            </select>
                            <div class="input-group-append">
                                <label class="input-group-text" for="inputGroupSelect02">Hari</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pelanggan">Nama Pelanggan</label>
                        <input type="text" style="width:100%!important;margin-bottom:5px;" class="form-control" name="customer" id="customer" placeholder="Optional">
                            {{--<div class="form-check col-md-4">--}}
                                {{--<div class="custom-control custom-checkbox">--}}
                                    {{--<input type="checkbox" class="custom-control-input" id="customControlAutosizing">--}}
                                    {{--<label class="custom-control-label" for="customControlAutosizing">Non-member</label>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                    </div>
                    <div class="form-group">
                        <label for="pelanggan">Alamat Email Pelanggan</label>
                        <input type="email" style="width:100%!important;margin-bottom:5px;" class="form-control" name="email" id="email" placeholder="Optional">
                        <small id="emailHelp" class="form-text text-muted">Isi untuk mendapat pemberitahuan Laundry selesai</small>
                    </div>
                    <div class="form-group">
                        <label for="pelanggan">Tambahan/Ekstra</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="desk" onfocus="document.getElementById('ekstra10k').setAttribute('selected','selected')" placeholder="Selimut, Sprei, ..">
                            <select class="custom-select col-md-4" name="biaya" id="inputGroupSelect02">
                                {{--<option selected disabled>Choose...</option>--}}
                                <option selected disabled>Harga</option>
                                <option value=5000>Rp.5.000</option>
                                <option id="ekstra10k" value=10000>Rp.10.000</option>
                                <option value=15000>Rp.15.000</option>
                                <option value=20000>Rp.20.000</option>
                            </select>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>
            <div class="col-md-1"></div>
            <div class="sub-content col-md-4" style="background-color:rgb(123,123,123,0)">
                <h1>On-process</h1>
                <hr>
                @foreach($data as $item)

                    <div class="on-process-panel row" id="process{{$item->id_trans}}" data-toggle="modal-" data-target="#exampleModal">
                        <div class="col-3" style="padding:0px">
                            No: <span class="value id">{{$item->id_trans}}</span>
                        </div>
                        <div class="col-4" style="padding:0px">
                            DD: <span class="value">{{DateTime::createFromFormat("U", strtotime($item->duedate))->format('d/m')}}</span>
                        </div>
                        <div class="progress-button">
                            @if(session()->has('ekstra'))
                                <a href="#" class="fas fa-plus info"><span class="caption">Ekstra</span></a>
                            @endif
                                <a href="{{route('transaksi.done', ['id'=>$item->id_trans])}}" class="fas fa-check done collapsed" onclick="document.getElementById('process{{$item->id_trans}}').classList.toggle('process-removed');"><span class="caption">Selesai</span></a>
                        </div>
                    </div>

                @endforeach
                @if($any)
                    <center><a href="{{route('transaksi.index')}}" class="link">Lihat Semua</a></center>
                @else
                    <a class="link">Tidak ada laundry dalam antrian</a>
                @endif
            </div>
        </div>
    </div>


@endsection

resources/views/admin/user.blade.php
@extends('admin.index')

@section('content')

    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <div>
                        <h2 class="card-title">Daftar Pegawai</h2>
                    </div>
                    <hr>
                    <div>
                        <button class="btn btn-primary" data-toggle="modal" data-target="#codeOnly">Kode Laundry</button>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                        <th>Nama User</th>
                        <th>Role</th>
                        <th>E-mail</th>
                        <th>Terdaftar</th>
                        <th>#</th>
                        </thead>
                        <tbody>
                                            {{--{{dd($data)}}--}}
                        @foreach($data as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>{{is_null($item->role)?'-':$item->role}}</td>
                                <td>{{$item->email}}</td>
                                <td>{{$item->created_at}}</td>
                                <td>
                                    @if(is_null($item->role))
                                        <a href="{{route('user.hire', ['$id_pegawai'=>$item->id_pegawai, 'role'=>2])}}">
                                            <button class="btn btn-primary">Terima</button>
                                        </a>
                                    @else
                                        <form action="{{route('user.destroy', ['id'=>$item->id_pegawai])}}" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-light">Keluarkan</button>
                                        </form>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    {{--table.table.table-striped.table-hover>(thead>(th*5))+tbody--}}
                </div>
            </div>
        </div>
    </div>

@endsection